### ISSUE TITLE
Esc to exif +  Double-Clicking to reset + Drag-Moving when not overflow

### ISSUE THREAD

**Issue by dnknn** [Deathamns/Viewhance#70] opened 2020-08-08 19:31 UTC
Viewhance is a powerful independent tab/window image viewer !
- ## ❶. Add a ⚙: Use `Esc` to close/exit the tab instead of reset the image.

> It is also very easy to reset the image directly with the mouse (click/double-click).
> `Esc` Quickly exit more easily, more than <kbd>Ctrl+W</kbd>
 <br>
<details>
<summary>Details: Click to view demo</summary>

![208_09031054](https://user-images.githubusercontent.com/10995302/89717962-f63eaa80-d9ed-11ea-9b52-43102b9f529d.png)
![208_09032802](https://user-images.githubusercontent.com/10995302/89718336-58001400-d9f0-11ea-8542-ae0328b8a07f.png)

</details>

#### https://greasyfork.org/scripts/16403    
<details>
<summary>This script is also a separate tab for independent images</summary>

![208_09032339](https://user-images.githubusercontent.com/10995302/89718193-bd9fd080-d9ef-11ea-9313-b4238598f762.png)

</details>

---
- ## ❷. Can you increase the mouse event of the `Double-Clicking` default behavior?
**`Double-Clicking`** also can **reset** the image to its original form, or quits from free-zoom.

---

- ### ❸. Add a ⚙: drag-moving the image when not overflow.

if ☑ , you can also drag-move the image, when the image does not overflow the Window, 
In other words, when there is **no** `body {overflow: scroll}` ,  no scroll bar,  you can also drag-move the image.

⚠drag-moving with not overflow, the cursor does not need to be changed.

<details>
<summary>Details: Click to view demo</summary>

![drag-moving](https://user-images.githubusercontent.com/10995302/89725075-e64eb700-da3d-11ea-8cf8-ead2546a9cf3.gif)

</details>

----
- ## ❹. Compatible with other extension.
Recommend a extension to zoom images/videos on any page, It is also a very useful and great extension.
## [֎In Zoom ᐝ](https://chrome.google.com/webstore/detail/oppcghdbglmbhhobfoodedhokbadlenh)  &emsp;&emsp;https://kpion.github.io/inzoom/

![208_09154941](https://user-images.githubusercontent.com/10995302/89727485-ff646180-da57-11ea-94f1-db806258aa60.png)

`Viewhance` and `InZoom`, can the two be perfectly compatible?
`InZoom` has 2 useful functions on the independent tab/window.
① the default zoom of `InZoom` is small scale zoom, the default zoom of `Viewhance` is large scale zoom.
② After zoom, `InZoom` can dragging, even not overflow window.

![208_09144312](https://user-images.githubusercontent.com/10995302/89726596-ab08b400-da4e-11ea-844e-55a4475e127a.png)
![208_09150234](https://user-images.githubusercontent.com/10995302/89726809-603c6b80-da51-11ea-9b59-d5f609201906.png)

For example, in `InZoom`, the zoom shortcut is set to `Shift+🎡`,
And sometimes in the independent tab/window, want to use InZoom's `Shift+🎡` to zoom.
### 💥 But it doesn't working at all,  The problem is with `Viewhance`, 
because `Viewhance` completely takes over the all 🎡,  e.g. Alt+🎡 /  Shift+🎡  / Alt+Shift+🎡 Ctrl+Shift+🎡 / Ctrl+Alt+🎡

So, can `Viewhance` remove `Shift+` and `Alt+` ?
In other words, the zoom shortcuts available for `Viewhance` are only 🎡 or Ctrl+🎡 or Ctrl+Shift+🎡, 
other key combinations will not be used/triggered for zooming.

I don't know the code, but I know there are similar key pressing logic.
````
if (event.ctrlKey==1)
//The default behavior is that all keystrokes combined with Ctrl will trigger, 
e.g. 	Ctrl+Shift		or 	Ctrl+Alt  	or   Ctrl+Shift+Alt	,	all will be triggered.
 ````	

 ````	
if (event.ctrlKey==1 && !event.shiftKey)		// But if add		!event.shiftKey 	, 
		//		then, Ctrl+Shift or Ctrl+Alt+Shift  will not be triggered.
 ````	

----
### Or `Viewhance` can add zoom shortcuts with different zoom logic ?
shortcut | behavior/action | description
:---: |--- |--- |
 🎡 / Ctrl+🎡 / Ctrl+Shift+🎡 | **large** scale(per) zoom | **Ie:** current default behavior
 Shift+🎡 | **small** scale(per) zoom  | newly added behavior 🆕 (Just like `InZoom`)

**Comment by Deathamns** [comment] 2020-08-10 08:25
1. I'll see.
2. No, I don't use double clicking at all because it would interfere with basic click features. You can reset from the menu or Esc.
3. Duplicate of #69
4. I'll think about Shift+Scroll for smaller scales.

**Comment by Deathamns** [comment] 2020-08-10 14:11
1. I've decided against this.
4. 4d5dbac You can configure your primary and secondary zoom steps (active via Shift).

**Closed by Deathamns** 2020-08-10 14:11 UTC

**Comment by dnknn** [comment] 2020-08-10 14:38
> 1\. I've decided against this.  

Which point are you referring to, `Esc` to close tab?


> 2\. You can configure your primary and secondary zoom steps (active via Shift).
thank you very much. I don't  know code at all, but it feels like it should be able to achieve small zoom with Shift+wheel.

**Comment by Deathamns** [comment] 2020-08-10 14:47
> I think it should be easy to add the option to close the tab with Esc

I don't see the point of replicating a really basic browser feature for this little convenience. Also, I would have to use the tab closing API for each browser (because not every one of them can close the tab with `window.close()`). So, no.

>  I don't know code at all, but it feels like it should be able to achieve small zoom with Shift+wheel.

You don't need to code anything, it is an option: `Zoom step; snap points`.

**Comment by dnknn** [comment] 2020-08-10 15:13
Wow,  I collocation with Tampermonkey [script](https://greasyfork.org/scripts/16403) additional.
Thanks♪(･ω･)ﾉ
